Function

In [1]:
import numpy as np
def get_scaled(data):
    data = np.array(data)
    result = (data.transpose() - data.min(axis=1)) / (data.max(axis=1) - data.min(axis=1))
    result = result.transpose()
    return result


Input

In [2]:
np.random.seed(1)
data = np.random.uniform(-1000, 1000, (3, 5))
print(data)

[[-165.95599059  440.64898688 -999.77125037 -395.33485474 -706.48821837]
 [-815.32281046 -627.47957724 -308.87854591 -206.46505154   77.63346801]
 [-161.61097119  370.43900079 -591.09550054  756.23487278 -945.2248136 ]]


Output

In [3]:
print(get_scaled(data))


[[0.57886944 1.         0.         0.41962504 0.20360935]
 [0.         0.21036106 0.5671546  0.68184498 1.        ]
 [0.46055387 0.77325594 0.20813265 1.         0.        ]]


In [4]:
data = [
    [25, -19, 35, 90, 73],
    [14.86452745, -26.8915466, -4.42219305, 6.3526264, 7.88297253],
    [0, 0, 1, 0, 1],
    [837, 302, 790, 271, 796],
    [49.97, 49.94, 51.37, 50.97, 51.29]]

print(get_scaled(data))

[[0.40366972 0.         0.49541284 1.         0.8440367 ]
 [1.         0.         0.53810982 0.79615179 0.83280145]
 [0.         0.         1.         0.         1.        ]
 [1.         0.05477032 0.91696113 0.         0.92756184]
 [0.02097902 0.         1.         0.72027972 0.94405594]]
